name: Build GUI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  gui-build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install poetry
        run: |
          python -m pip install pip wheel pipx --upgrade
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: poetry

      - name: Install Python Dependencies
        run: poetry install

      - name: Build GUI
        run: poetry run python GUI/build.py

      - name: Test GUI
        shell: pwsh
        run: ./dist/AVRGUI.*.exe --test-bundle

      - name: Upload GUI Artifact
        if: github.event_name != 'push'
        uses: actions/upload-artifact@v3
        with:
          name: GUI
          path: dist/*.exe

      - name: Create Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          files: dist/*.exe
