name: Build GUI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install poetry
        run: |
          python -m pip install pip wheel pipx --upgrade
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: poetry

      - name: Install Python Dependencies
        run: poetry install --only main

      - name: Get Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build GUI
        run: poetry run python build.py --version ${{ env.SHORT_SHA }}

      - name: Test GUI Bundle
        shell: pwsh
        run: ./dist/AVRGUI.*.exe --test-bundle

      - name: Upload GUI Artifact
        if: github.event_name != 'push'
        uses: actions/upload-artifact@v3
        with:
          name: GUI
          path: dist/*.exe

      - name: Create Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.SHORT_SHA }}
          files: dist/*.exe
